### ISSUE TITLE
Animation.js:76 Uncaught TypeError: window.cancelTimeout is not a function

### ISSUE THREAD

**Issue by simplelc** [angrycat9000/webapp-menu#10]
html source:
<wam-toolbar open="" closeon="none" useanimation="true" >
        <wam-item label="file" id="menuFileBar" showtoolbarlabel="" >
            
        </wam-item>    </wam-toolbar>
    <wam-nestedmenu controlledby="menuFileBar" style="z-index: 1000;" id="menuFile">
        <wam-item label="localsave" action="localSave" ></wam-item>
        <wam-item label="serversave" action="serverSave"></wam-item>
    </wam-nestedmenu>  

problem:
when click menu item it will work ,but it will show error in console , how to fix this problem?

Animation.js:76 Uncaught TypeError: window.cancelTimeout is not a function
    at a.cleanup (Animation.js:76)
    at a.complete (Animation.js:140)

**Comment by angrycat9000** [comment]
Thanks for finding this.  I just pushed [a change that fixes](https://github.com/angrycat9000/webapp-menu/commit/f228db0e85e905011fa7dff26fe3b8270031ca2a) it and published a new version 2.2.6

Let me know if you find any other problems.
